version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: /packages/common/
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: /packages/agents/
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: /packages/backend/
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: /packages/frontend/
    schedule:
      interval: monthly
